openapi: "3.0.0"
info:
  version: 1.0.0
  title: Habit Tracker API
paths:
  /login:
    post:
      summary: Get JWT Token
      responses:
        '200':
          description: A JWT Token
  /habits:
    get:
      summary: List all habits
      responses:
        '200':
          description: A JSON array of habits
